### ISSUE TITLE
Multi-gpu training support?

### ISSUE THREAD

**Issue by ChengshuLi** [tensorflow/agents#11]
Hi tf-agents team,

Thanks for answering all of my previous questions. 

Does tf-agents support multi-gpu training? If so, is there any recommendation you could give me to achieve this (i.e. which files to consider modifying)? I found these two resources:
https://www.tensorflow.org/guide/using_gpu#using_multiple_gpus
https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py

I have only done multi-gpu training in PyTorch and Keras and I am still learning more about that of TF. 

Thanks again.

**Comment by oars** [comment]
We haven't done much to optimize for multi-gpu yet. For now our current plan moving forward is to finish support for TF2.0 across all our agents (including some unreleased ones) and then we will start looking at accelerators and distributed training.

In most cases data collection is the bigger bottleneck which is why we haven't focused to much on accelerators yet, but regular resources for GPUs in TF should still apply.
