### ISSUE TITLE
Add Python type hints

### ISSUE THREAD

**Issue by Tautvis** [tensorflow/agents#127]
Adding python [type hints](https://docs.python.org/3/library/typing.html) would ease adaption of the library. Additionally, it would allow better use of the tools (i.e. PyCharm, Jupyter Notebook).

I'm not entirely sure what would be the impact on python 2.x support but given that python 2.x end-of-life is scheduled on 1st Jan 2020 perhaps that wouldn't pose a problem?

**Comment by marek-at-work** [comment]
Disclaimer: This is just my personal opinion (I don't work on TFA).

While having type hints sounds like nice-to-have feature on the paper, actual benefit might not be as large as it might seem. I see three main issues:
1) In many cases the type is obvious from name and any other type will raise some error anyways.
2) There are numerous cases where it is not even possible to specify helpful type annotation. For example, TFA uses nest heavily throughout the code base which cannot be annotated properly.
3) Type annotations add a lot of visual clutter to the code which may become less readable. Note that TFA code has 80 chars line limit.

Another minor reason might be slowdown of build times due to type inference and checking. While this might sound silly, it is a thing to consider.

I would like to see some examples where type annotations can actually avoid some common mistakes. For example, I do not find annotations like this helpful:
```
def __init__(self,
    ...
    emit_log_probability: bool = False,
    automatic_state_reset: bool = True,
    name: typing.Optional[typing.Text] = None):
```

**Comment by tfboyd** [comment]
We have added types to a lot of TFA in 2020 and especially in the new[ Actor/Learner API](https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/train); which is about to move out of experimental.  I am closing old issues and I think we also make progress on this one and are committed to using typing going forward where it makes sense.
