### ISSUE TITLE
Is this way of masking TD error/loss correct?

### ISSUE THREAD

**Issue by Rowing0914** [tensorflow/agents#134]
Hi,

I've just noticed that currently TD error/loss are computed as following way
- https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/dqn_agent.py#L393
- https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/dqn_agent.py#L395

instead of going like https://github.com/google/dopamine/blob/master/dopamine/agents/dqn/dqn_agent.py#L293

```python
self._replay.rewards + self.cumulative_gamma * replay_next_qt_max * (
        1. - tf.cast(self._replay.terminals, tf.float32))
```

And the `agents`'s implementation seems a bit weird to me because if we mask td loss/error then whenever a sample at a specific time has been a terminal state, we would not learn from that sample at all, rather we'd get 0 for them, right? so I am wondering if this is okay.

**Comment by kbanoop** [comment]
We compute TD errors/loss from transitions in the form [time_steps, actions, next_time_steps]. 

time_step.is_last() occurs only at boundaries of episodes where we have invalid transitions, i.e. time_step.is_last and next_time_step.is_first. These are ok are to remove from the loss.

Note that this doesnt filter out valid terminal transitions because for such transitions next_time_step.is_last rather than time_step.is_last
