### ISSUE TITLE
Passing custom arguments to suite_gym.load()

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/agents#137]
I want to pass custom arguments when loading my custom Gym environment using `suite_gym.load()`.
For e.g. I have an argument named `max_sim_time `that I can pass to `gym.make() `
`gym.make('PVDER-v0',max_sim_time=10.0)`

The above works because I have already specified it my register wrapper for my custom environment as shown below:

```
register(
    id='PVDER-v0',
    entry_point='gym_PVDER.envs:PVDER',
    kwargs={ 'max_sim_time' : 30.0 },
    max_episode_steps=500,)
```
However when I try passing `max_sim_time `as an argument to` suite_gym.load()`, I get unexpected keyword argument error.

```
from tf_agents.environments import suite_gym
import gym
import gym_PVDER
environment = suite_gym.load('PVDER-v0', max_sim_time=10.0)
```
Could you tell me the proper way to pass custom arguments to `suite_gym.load()`?
@seungjaeryanlee suggested a workaround to create a Gym environment wrapper that changes the `max_sim_time `parameter and pass the wrapper through `gym_env_wrappers `parameter.
I am not very clear on how to do this, so any examples would be much appreciated.

I feel a simple fix could be to add another argument in `suite_gym.load(environment_name,args)` and then pass it in _load()_ method in _suite_gym.py_ 
```
gym_spec = gym.spec(environment_name)
gym_env = gym_spec.make(args)
```
Is this a potential solution?

**Comment by oars** [comment]
Could you use [suite_gym.wrap_env](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/suite_gym.py#L79)? You can create an instance of your environment with all the custom arguments you need, then wrap it to expose it as a TFAgents environment.

**Comment by sibyjackgrove** [comment]
@oars thanks for the suggestion. Yes, I was able to use it. Here is what I did.

```
train_gym_env = gym.make('PVDER-v0',max_sim_time=30.0)
train_py_env = suite_gym.wrap_env(env,max_episode_steps=500)
train_env = tf_py_environment.TFPyEnvironment(train_py_env)
```
How if I didn't pass the  `max_episode_steps `argument to `suite_gym.wrap_env` I got following error:

> if max_episode_steps > 0:
>     127     env = time_limit_wrapper(env, max_episode_steps)
>     128 
> 
> TypeError: '>' not supported between instances of 'NoneType' and 'int'
>   In call to configurable 'wrap_env' (<function wrap_env at 0x0000016273115048>)

I am not sure if this is a bug or not. But it seems like since `max_episode_steps `is an optional argument, not including it should not cause a TypeError.

**Comment by oars** [comment]
Thanks for pointing that out! I think this is from when the `load` method got split. Let me fix it.

**Comment by sguada** [comment]
A PR which pass gym_kwargs to the gym environment is welcome.

**Comment by nataliedurgin** [comment]
Perhaps the `suite_gym.load()` default for `max_episode_steps` should be `0` instead of `None` as well to fully eradicate this bug? 
 
When using `suite_gym.load()` on a custom gym environment, for which no `max_episode_steps` is set, I am still getting this `TypeError`. 

This works:  `suite_gym.load('registered-custom-env', max_episode_steps=0)`
This does not:  `suite_gym.load('registered-custom-env')`

This is not surprising, since `suite_gym.load()` is calling `wrap_env()` and in that call, we propagate `max_episode_steps=None` which overrides the new `wrap_env()` default, `max_episode_steps=0` that has been corrected thus far in this ticket. 

See:
- https://github.com/tensorflow/agents/blob/2b75de602bd27665b9288250a774c32b01dbf8f3/tf_agents/environments/suite_gym.py#L35
- https://github.com/tensorflow/agents/blob/2b75de602bd27665b9288250a774c32b01dbf8f3/tf_agents/environments/suite_gym.py#L72

This does not seem to be a problem for many of the canonical gym environments, because `max_episode_steps` is set. E.g.

- `gym.spec('CartPole-v0').max_episode_steps` --> 200
- `gym.spec('CartPole-v1').max_episode_steps` --> 500

One might argue that `None` is a more intuitive default for max_episode_steps than 0. In which case, perhaps the comparison should just be `if max_episode_steps:` instead of, 

https://github.com/tensorflow/agents/blob/2b75de602bd27665b9288250a774c32b01dbf8f3/tf_agents/environments/suite_gym.py#L125

But I defer to those who understand the implications better than I do.
