### ISSUE TITLE
What is your plan for distributing RL agents over a huge cluster ?

### ISSUE THREAD

**Issue by karanchahal** [tensorflow/agents#14]
Is there some paper you're following or a document you refer to to scale RL agents? If so I would love to hear about what strategy you're using.

**Comment by egonina** [comment]
We are working on adding support for distributed data collection (running many parallel Actors that write experience trajectories to a shared replay buffer), similar to the IMPALA architecture (https://arxiv.org/abs/1802.01561).

**Comment by karanchahal** [comment]
Can I help with this ?

**Comment by ebrevdo** [comment]
Thanks for reaching out!  We plan to explore and experiment with different strategies before making this work public.  We want to ensure that when we release code, that it's easy to use, fast, and that covers a number of important use cases.  We're not there yet.

After the initial release we'll probably need help getting the orchestration working on various types of distributed systems (e.g. making it easy to launch experiments with kubernetes, docker, and various data backends).  We'll really appreciate help with those pieces, as well as beta testers!

Please keep track of this issue to get updates on the status of our work.  We can't make any promises or provide a detailed timeline, but it pieces will appear in this repository as they become ready and we'll update the issue.

**Comment by karanchahal** [comment]
Thank you for your response ! All this is very interesting. You can also refer to Pieter Abeel's paper on accelerating RL https://arxiv.org/abs/1803.02811. It was a good read. Looking forward to your release !

**Comment by karanchahal** [comment]
The above work was released concurrently with IMPALA. Unlike IMPALA, it proposes variations in popular RL algorithms like Deep Q and Policy Gradient methods instead of proposing a new algorithm. I would be very curious to know what worked and what didn't in your research !

**Comment by egonina** [comment]
Thank you for the pointer to paper. Similar to that work, we are focusing on variations on existing algorithms that we already support in TF-Agents (DQN, PPO etc.). We will update this issue as we make progress!

**Comment by tfboyd** [comment]
https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/distributed/examples/sac

The example lacks a lot of documentation, but includes what you need to have a distributed collect setup using Reverb with SAC as the example. The three process represents the parts we use to scale up to 100s of agents.  

While the work is not done as far as awesome documentation. I a closing due to the issue being older and this does provide what would be needed to get started and then ask a more specific question that we could answer. Please open another issue if you (the person reading this in the future) has a specific use case. We are having great success with Reverb (used by other RL libraries as well) to scale collection.
