### ISSUE TITLE
How can I access an underlying network?

### ISSUE THREAD

**Issue by hwiedPro** [tensorflow/agents#149]
Hi,
If I'm using e.g. the ActorDistributionNetwork. In which the network's structure is defined by parameters like`fc_layer_params`. If I want to configure the structure more freely e.g. with tf.keras.models.Sequential(...), how can I do this?
Why can't we pass a network model instead of those parameters?

**Comment by oars** [comment]
I just pushed a [colab](https://colab.sandbox.google.com/github/tensorflow/agents/blob/master/tf_agents/colabs/8_networks_tutorial.ipynb) on how to create custom networks, the concepts explained there should cover how to customize the ActorDistributionNetwork.

Hope that helps. Feel free to re-open otherwise.

**Comment by hwiedPro** [comment]
Thank you very much for your help :)
I will try it in the next weeks.
