### ISSUE TITLE
Wrong td_target calculation for next_time_step.is_last()

### ISSUE THREAD

**Issue by tbund** [tensorflow/agents#156]
Hi,

when calculating the critic loss of TD3 and DDPG agents, the critic network should produce a zero tensor for next_time_step.is_last(),
as for the last transition of an episodic task it must apply:
`td_target = reward` ~~`+ gamma * Q(s_i+1, a_i+1)`~~

Masking target_q_values similar to
https://github.com/tensorflow/agents/blob/42a0bc10fb318cd4a85c76688b8f713d47354e9f/tf_agents/agents/dqn/dqn_agent.py#L386-L387
could be a solution.

Probably further agents like SAC are affected.

**Comment by egonina** [comment]
Thank you for filing the issue. If you'd like, feel free to send a PR with the fix! 

cc @oars to verify

**Comment by marek-at-work** [comment]
I believe that the situation here is a little more nuanced. It actually depends on what kind of termination occurred. 

There are two cases:
1) Termination due to agent's behavior, say an collision or goal reach. In this case the discount in the last timestep is set to 0 effectively mask-out the Q.
2) Time-out due to limited time for episode, which is not considered agent's failure. In this case, discount is set to 1.0 on the last step and Q should be considered. If this is not set properly, you would be incorrectly expecting your agent to keep track of time and predict some different Q for the last step in case of time-out.

So I believe that the mask is effectively hidden in the discount `gamma`.

**Comment by oars** [comment]
Thanks @MarekAtGoogle for the clarification. I believe this outline is correct. You can see the discount being combined with gamma when the td_error is called: 

https://github.com/tensorflow/agents/blob/42a0bc10fb318cd4a85c76688b8f713d47354e9f/tf_agents/agents/dqn/dqn_agent.py#L368
