### ISSUE TITLE
Plot TF-Agents networks

### ISSUE THREAD

**Issue by Taxel** [tensorflow/agents#208]
I have been trying to plot the network of my PPO agent using this code:
```
tf.keras.utils.plot_model(
            actor_net, to_file='actor_net.png', show_shapes=True, expand_nested=True)
```
Unfortunately, this does not work as expected: It just outputs [this image](https://ibb.co/3pwRwLz), which is obviously not what I want.
I suspect this happens because the `ActorDistributionNetwork` does not subclass `tf.keras.Model` but an internal class of Keras.
Is it possible to plot `tf-agents` networks directly or do I have to create a different model with the same layer architecture to be able to plot the network structure?

**Comment by tfboyd** [comment]
I am closing due to being over a year old. I did fix something a while back that made I think network summary work. I wish I could say if this works or not. If you happen to use it again and it doesn't work ping this issue or open a new one. I am sorry there wasn't a resolution.

**Comment by DBraun** [comment]
This kind of works.
```python
actor_net._encoder._is_graph_network = True
tf.keras.utils.plot_model(
    actor_net._encoder, 'model_actor_net.png', show_shapes=True, show_layer_names=True, expand_nested=True
)
```

I'm having more difficulty getting it to work for the [critic_net](https://github.com/tensorflow/agents/blob/2857fbab6021969df99e7b1cd0f4ec66541c3dba/tf_agents/agents/sac/examples/v2/train_eval.py#L154). I might need to do it the long way:
```python

fake_obs = tf.nest.map_structure(lambda x:
    keras.Input(shape=x.shape, dtype=x.dtype, name=x.name),
    observation_spec)

fake_actions = tf.nest.map_structure(lambda x:
    keras.Input(shape=x.shape, dtype=x.dtype, name=x.name),
    action_spec)

fake_output = critic_net((fake_obs, fake_actions))

fake_model = tf.keras.Model(inputs=[fake_obs], outputs=[fake_output])

tf.keras.utils.plot_model(
    fake_model , 'model_critic_net.png', show_shapes=True, show_layer_names=True, expand_nested=True
)
```

But then I get some errors, possibly related to it running in eager execution mode.

For instance you can't do
```python
from tensorflow.python.framework.ops import enable_eager_execution
enable_eager_execution()  # on by default?
a = tf.keras.layers.Input(shape=(4))
b = tf.keras.layers.Dense(3)
b(a)
```
`TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.`

But this kind of thing is happening in the forward passes of the critic_net's [mlp layers](https://github.com/tensorflow/agents/blob/2857fbab6021969df99e7b1cd0f4ec66541c3dba/tf_agents/agents/ddpg/critic_network.py#L123-L145) which do Flatten() and Dense() on KerasTensors with shape (**None**, some_integers....). So it errors on `fake_model = tf.keras.Model(inputs=[fake_obs], outputs=[fake_output])`

Also, the .summary() method isn't working great either because it doesn't show the nested details of the networks. I'd be happy with either plotting or summary printing, as long as it works for both the actor_net and critic_net.

Update:
I got ok results by switching from utils.mlp_layers to using encoding networks inside the critic network. Then I do the same thing I described above with actor_net.
