### ISSUE TITLE
concatenation layer and replay buffers

### ISSUE THREAD

**Issue by niklasnolte** [tensorflow/agents#287]
Hi,
I am trying to run a dqn agent with an environment where my `observation_spec` is a collection of specs (list or tuple). my q-network thus needs a `preprocessing_combiner`. First i chose `tf.keras.layers.Concatenate()`, which only works if my `observation_spec` is a list. However, when trying to implement a replaybuffer (as done in https://github.com/tensorflow/agents/blob/master/docs/tutorials/1_dqn_tutorial.ipynb), `ReplayBuffer.as_dataset()` tells me to use tuples for my spec collections.  
My current solution is switching out the preprocessing_combiner to 
`tf.keras.layers.Lambda(lambda x:tf.keras.layers.Concatenate()(list(x)))`, but this feels more like a workaround than a fix..

I would be surprised if i was the first one with this problem, unless i am doing something conceptually wrong?

**Comment by ebrevdo** [comment]
Yes; it's a bit sad that we're forced to use tuples but that's a limitation of tf.data - arrays are not allowed because they get converted to tensors.  Your other options are to add preprocessing_layers which are just tf.keras.layers.Layer() - this will be an identity pass-through, and the resulting tensors passed to the combiner will be an actual list.

Let me know if this doesn't solve the problem.
