### ISSUE TITLE
Why does the action spec for a DqnAgent require a minimum of 0?

### ISSUE THREAD

**Issue by caseyjconger** [tensorflow/agents#310]
Perhaps a silly question.

I tried creating a DqnAgent, but I get the following error:

`ValueError: Action specs should have minimum of 0, but saw: [array(-1, dtype=int32)]
  In call to configurable 'DqnAgent' (<function DqnAgent.__init__ at 0x7f43b7d58a70>)
`

Why is there this restriction on the actions? I had defined actions schematically as : 
```
{
    +1: go_up,
     0: do_nothing,
    -1: go_down
}
```

Thanks!

**Comment by samfishman** [comment]
This is due to a quirk of how the DQN agent works internally. (We use actions as indexes into a table of Q values.) We have an internal issue open to track this, but in the meantime, I would recommend just incrementing your actions by 1 :). Closing this because it is already being tracked, but we will ping here when it is resolved.

**Comment by oars** [comment]
You can use environments.wrappers.ActionOffsetWrapper to avoid having to change your env.

**Comment by caseyjconger** [comment]
@samfishman  Thanks for the quick response. I didn't see the comment in the code until after I raised the issue. I was racking my brain trying to think of a theoretical reason for this. So, I'm just glad I'm not crazy.

@oars Excellent! Thanks.
