### ISSUE TITLE
How to use PPO with minibatch and compute_value_and_advantage_in_train ?

### ISSUE THREAD

**Issue by jrabary** [tensorflow/agents#408]
The master version of PPO seems to have a new option to train PPO on mini batches. 
In the documentation we have 

```
compute_value_and_advantage_in_train: A bool to indicate where value
 prediction and advantage calculation happen.  If True, both happen in
 agent.train(). If False, value prediction is computed during data
 collection. This argument must be set to `False` if mini batch learning
 is enabled.
```

I'm trying to figure out how it works and what is missing currently. 

Here is my first attempt :

After setting `compute_value_and_advantage_in_train=False` I changed the `train_step` in the PPO V2 example as follow:

```
    dataset = replay_buffer.as_dataset(sample_batch_size=10, num_steps=100, single_deterministic_pass=True)

    def train_step():
        for experiences, _ in dataset:
          loss = tf_agent.train(experience=experiences)
      return loss
```

This produces the following error:

```
ValueError: Tensors and specs do not have matching structures:
  Trajectory(step_type=., observation=., action=., policy_info=DictWrapper({'dist_params': DictWrapper({'loc': ., 'scale': .}), 'value_prediction': .}), next_step_type=., reward=., discount=.)
vs.
  Trajectory(step_type=., observation=., action=., policy_info=DictWrapper({'dist_params': DictWrapper({'loc': ., 'scale': .}), 'value_prediction': ., 'return': ., 'normalized_advantage': .}), next_step_type=., reward=., discount=.)
```

What I understand is that I need to compute the return and advantage somewhere before building the mini batches and calling the train step. 

Where is the best place for that and shouldn't be `agent._preprocessing(experience)` a public method ?

**Comment by jrabary** [comment]
Here is the current change I made for the example. I'm not sure whether it is the best solution :

```
    def preprocess(experiences, unused):
      return tf_agent._preprocess(experiences) 
      
    dataset = (replay_buffer.as_dataset(sample_batch_size=10, num_steps=1001, single_deterministic_pass=True)
        .map(preprocess))
```

```
      start_time = time.time()
      collect_driver.run()
      collect_time += time.time() - start_time
      
      # start_time = time.time()
      for e in range(num_epochs):
        count = 0
        for experiences in dataset:
          total_loss, _ = tf_agent.train(experience=experiences)
          count += 1
      replay_buffer.clear()
      train_time += time.time() - start_time
```

**Comment by summer-yue** [comment]
Thanks for the question. You can use `tf_agent.preprocess_sequence` to perform advantage calculation on a sequence of trajectories. This is the public method that calls `agent._preprocessing` under the hood. It's defined in the TFAgent base class. Note that preprocessing needs to happen before the data gets split into mini batches (since advantage calculation requirers longer sequences).

The error you saw with the mismatched spec is just saying that the agent.train() function expects the advantage fields to be filled in, but the data fed into the function doesn't have the advantage fields.  We will add more documentations on this. Hope this helps.

**Comment by jrabary** [comment]
Thanks for your answer. It really helps. 

I have some more thoughts 

> Note that preprocessing needs to happen before the data gets split into mini batches (since advantage calculation requirers longer sequences).

I understand this fact. So ideally, I should run `preprocess_sequence` with the output of `replay_buffer.gather_all`. I found two problems here: 1) `gather_all` is marked deprecated, 2) `dataset.map` is for me the best way to go but on has somehow to split the data here.

What about having a callback in the driver that gets called when the episode is done to perform all these computation ? Currently we have callbacks on transition so why not on episode as well.

**Comment by jrabary** [comment]
Just found this in the documentation of `ReplayBuffer`

```
sequence_preprocess_fn: (Optional) fn for preprocessing the collected
        data before it is split into subsequences of length `num_steps`.
        Defined in `TFAgent.preprocess_sequence`.  Defaults to pass through.
```

What I understand is that I just have to pass `preprocess_sequence` here and voilà! Am I correct ?

Further more, in this situation ` EpisodicReplayBuffer` is maybe the best option.

**Comment by summer-yue** [comment]
Good questions. I am not sure which replay buffer you are using right now, but very likely that `replay_buffer.as_dataset()` with `sequence_preprocess_fn` isn't supported. We are pushing out a new replay buffer in July using Reverb (https://deepmind.com/research/open-source/Reverb) and that'd support the `sequence_preprocess_fn` feature very well.

For now, what you have `as_dataset` with `num_steps=1001` and then calling map with the `preprocess_sequence` looks good to me (given that your environment's episode length is <1001, otherwise it'd be better to increase this number). Stay tuned for the `ReverbReplayBuffer` launch soon, as that'd make what you're trying to do a lot nicer :)

Feel free to follow up with other questions. Happy to help.

**Comment by summer-yue** [comment]
Seems like this is resolved?

**Comment by summer-yue** [comment]
ReverbReplayBuffer is now open sourced! You may use that as a permanent solution now :)(https://github.com/tensorflow/agents/blob/master/tf_agents/replay_buffers/reverb_replay_buffer.py)
