### ISSUE TITLE
tf-agents-nightly installed on colab seems very different from the master branch

### ISSUE THREAD

**Issue by chokosabe** [tensorflow/agents#467]
tf-agents-nightly installed on colab seems very different from the master branch. The experimental examples folder is missing . Not 100% if this is a colab issue or a tf-agents issue.

**Comment by kbanoop** [comment]
@tfboyd Can you PTAL?

**Comment by tfboyd** [comment]
The colab install `tf-agents` not `tf-agents nightly`.  This is because tensorflow.org copies the colabs into https://www.tensorflow.org/agents/tutorials/2_environments_tutorial.  In a perfect world the github would install tf-agents-nightly and tensorflow.org tf-agents but that makes it harder to push smaller changes automatically to tensorflow.org and requires branches and merges that just take up time. I am sorry if this sounds kind of "handwavy" but I have a long history of being overly honest. 

We verify that the colabs work with both nightly and stable. We also release stable each time a new tensorflow version is released.  You can change it in the colab by switching:

`!pip install tf-agents` to `!pip install tf-agents-nightly[reverb]` (this will also likely install tf-nightly and also adds reverb which much of experimental uses)

That will allow you to access everything in experimental.

**Comment by chokosabe** [comment]
Thanks for the replay @tfboyd. Tried your suggestion above and still the same issue. Can you give some more details on how you guys verify that colab works with nightly? There are clearly folders missing when I install nightly on Colab. It doesn't match the master branch at all.

Thanks.

A.

**Comment by chokosabe** [comment]
I can confirm I am seeing this behaviour locally. The tf-agents-nightly build isn't using the master branch.

**Comment by tfboyd** [comment]
@chokosabe 
Can you share how you confirm? What command are you running that is not working. It is really hard to debug the statement "There are clearly folders missing when I install nightly on Colab". I know it can be frustrating but if you share the exact python command you are trying I can verify the problem and hopefully the solution without ambiguity. 

The build runs nightly and is built from head. The colabs are tested using the docker and this script `https://github.com/tensorflow/agents/blob/master/tools/test_colabs.py` after the nightly is installed. The devrel team runs a similar script but they run against tf stable and tf-agents latest stable.

**Comment by tfboyd** [comment]
One wild guess but I would still like to see what is not working.  You cannot import (I did not try but without the __init__.py it seems unlikely to work) the experimental packages because there isn't an init.py file. I used the experimental SAC to run 50+ tests over Labor Day Weekend for 5 different mujoco envs so we can updated the README with a bunch of data.  I am going to followup on if that is intentional. I suspect it is just an accident based on how the code was ported.

**Comment by lucifer2288** [comment]
The same issue happened to me

**Comment by tfboyd** [comment]
@lucifer2288  and @chokosabe  There is a chance I can fix the problem but I need a repro. What are you trying to do? Can you share a snippet?

```python
import blah.blabh.blah as y

y.something
```
We left out the __init__.py from those folders some what on purpose, but if you want to use the examples in a way we did not expect I can likely address it if I can get some confirmation. But I really cannot do much without more information.

**Comment by chokosabe** [comment]
A really simple test would be:

from tf_agents.experimental.examples.ppo import ppo_learner

ppo_learner.PPOLearner

this doesn't trigger an import error on master but does on a nightly install

**Comment by tfboyd** [comment]
Perfect. That is what I thought. Just need to add __init__.py to the
folders so it can be imported. We chatted as a team and this makes sense to
do.  I will add them next week and ping this thread. Nightly is building
from master, there is zero doubt of that.

**Comment by chokosabe** [comment]
It might be more than that, navigation to the folders (in the case above tf_agents/experimental) shows that the /examples folder isn't there.

**Comment by tfboyd** [comment]
I will verify end to end. It could be excluded from the pip build for some
reason. I will resolve it and verify in a colab. This is a good change to
make and makes it easier to play with the new API.

**Comment by tfboyd** [comment]
b/169060496  Internal track. I hope to get the situation resolved today for tomorrow's nightly build.

**Comment by tfboyd** [comment]
Ok adding __init__.py was enough. The whl packager seems to look for that, which is why you don't see it at all. The change it in review and I will ping this bug when the PR is submitted and I see it in nightly. I hope 24 hours.  My simple test is:

```python
import tf_agents.experimental.examples.sac.haarnoja18.sac_train_eval
```

The gin files are not loaded so you will have to call it by including the args you want as params to `train_eval`.  I also made changes to include the PPO code and distributed collect SAC example I have not tested yet.

**Comment by tfboyd** [comment]
Alright super close. After adding the __init__.py a new test was added for PPO and that test was failing in open source but not internally. I sorted that out and now I am waiting for the final code change to be reviewed and everything should be in place. Who would have thought adding 6 init.py files would take like 3 days. Actually I did but I am way to aware of what goes wrong.

I like to keep these things updated when I am actively working.

**Comment by tfboyd** [comment]
Ok tested and resolved.  @chokosabe

I logged into the colab and this worked, well I get a mujoco error but I suggest using my [mujoco docker](https://github.com/tensorflow/agents/blob/master/tools/docker/ubuntu_1804_mujoco) if you find it useful. I have not tried the notebook with mujoco docker but notebook is installed. 

```python
!pip install tf-agents-nightly[reverb]
!pip install tf-nightly

import tf_agents.experimental.examples.sac.haarnoja18.sac_train_eval
# Fails with a mujoco error but clearly loads.
tf_agents.experimental.examples.sac.haarnoja18.sac_train_eval.train_eval('/tmp')
```

Ping this thread if you have issues and I can reopen but I think I have fixed the issue according to the information provided.

**Comment by chokosabe** [comment]
Tested this on Colab. Looks ok; all the relevant files now show up on tf-nightly install. 

Many thanks.
