### ISSUE TITLE
Documentation clarification: What does log_probability mean in DqnAgent and why is it scalar?

### ISSUE THREAD

**Issue by ninadmore** [tensorflow/agents#498]
In the tf_agents [DqnAgent docs](https://www.tensorflow.org/agents/api_docs/python/tf_agents/agents/DqnAgent), there is a parameter in the constructor called emit_log_probabilities but the explanation is just "Whether policies emit log probabilities or not."

What does log_probabilites actually mean in this case? Despite having many possible actions in my actions spec why is it a scalar ([code example](https://stackoverflow.com/questions/63555940/can-tf-agent-policy-return-probability-vector-for-all-actions))?

**Comment by ormandi** [comment]
Thank you for your question.

Actually, this is a parameter of the policy (but it is passed through the agent since the underlying policy is created by the agent). So, the parameter is better documented in the [base class of the policies called `tf_policy`](https://github.com/tensorflow/agents/blob/master/tf_agents/policies/tf_policy.py#L144-L148). It basically decides if the logarithms of the probabilities over the actions (aka `log_probabilities`) are emitted into the `policy_info` as auxiliary information ([code](https://github.com/tensorflow/agents/blob/master/tf_agents/policies/tf_policy.py#L565-L573)).

So, just to directly respond to your question, the output of the policy does not change (i.e. it remains scalar) by changing this parameter. Rather the parameter determine if the mentioned auxiliary information is written or not.

Hope this helps.

In terms of fix, I would not change the documentation for only this agent (we have multiple with similar comments). If it seems reasonable we may change these for all of the agents in a separate PR to handle all of these in the same way.
