### ISSUE TITLE
need magic numbers

### ISSUE THREAD

**Issue by yiyinying** [tensorflow/agents#500]
replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=tf_agent.collect_data_spec,
    batch_size=train_env.batch_size,
    max_length=replay_buffer_capacity)

driver = dynamic_step_driver.DynamicStepDriver(train_env, collect_policy, [replay_buffer.add_batch],
                                               num_steps=1000)
dataset = replay_buffer.as_dataset(sample_batch_size=100, num_steps=2, num_parallel_calls=4).prefetch(3)

replay_buffer max_length,dirver num_steps,dataset sample_batch_size,for changes in sample_batch_size, an error is always reported

**Comment by yiyinying** [comment]
error is:
Function call stack:
train

**Comment by yiyinying** [comment]
error is:
Function call stack:
train

**Comment by ormandi** [comment]
Thank you for the comment.

TBH, not fully understand the error you mentioned. However, I've noticed that it is related to `TFUniformReplayBuffer`. Since, we are moving away from that implementation in favor of `Reverb`, I'd encourage you to take a look into our Reverb replay buffer based examples.

To see a working example, a good starting point would be the SAC example. [Here](https://github.com/tensorflow/agents/blob/master/tf_agents/experimental/examples/sac/haarnoja18/sac_train_eval.py#L150-L164) you can see:

  * how to set up an in-process Reverb server,
  * perform data collection (using `rb_observer` in the `initial_collect_actor` and `collect_actor`), and
  * perform sampling for the agent (using `experience_dataset_fn` in the `agent_learner`).

Potentially, you may also want to look into the [`reverb_replay_buffer_test.py`](https://github.com/tensorflow/agents/blob/master/tf_agents/replay_buffers/reverb_replay_buffer_test.py).

Please let us know if you run into problems with Reverb-based replay buffer.
