### ISSUE TITLE
Reward discount factor defined in environment compared to defined in environment

### ISSUE THREAD

**Issue by biplavc** [tensorflow/agents#503]
When defining the agent, we can define the reward discount factor as `gamma`

https://github.com/tensorflow/agents/blob/755b43c78bb50e36b1331acc9492be599997a47f/tf_agents/agents/dqn/dqn_agent.py#L113

In case we define a discount factor for future rewards in the environment itself as 
`return ts.transition(np.array([self._state], dtype=np.int32), reward = award, discount=1.0)`, ([link](https://www.tensorflow.org/agents/tutorials/2_environments_tutorial#usage_examples)) which value will be used reward discount factor as both of them (the `gamma` in agent and `discount` in environment) refer to the same value of reward discount factor ?

**Comment by agreenb** [comment]
The `gamma` and `discount` values are [multiplied](https://github.com/tensorflow/agents/blob/755b43c78bb50e36b1331acc9492be599997a47f/tf_agents/agents/dqn/dqn_agent.py#L465) to create the discount in the TD target. Feel free to reopen if you have more questions about this.

**Comment by biplavc** [comment]
So in order to have a general scenario where the discount factor of the future rewards is dictated solely by `gamma`, can we keep the `discount` in the environment as 1 and specify the needed discount in `gamma` ?

**Comment by agreenb** [comment]
Generally, `discount` is 1 for every step except for the final step, where it is 0 since we only want to include the immediate reward. Here, it ensures that the last step's TD target doesn't include future expected rewards.

`gamma` refers to the importance of future rewards versus immediate ones and is a constant value. Without `discount`, the last step would still include future expected rewards * gamma.
