### ISSUE TITLE
Return Critic values for states and actions for SAC

### ISSUE THREAD

**Issue by ayansengupta17** [tensorflow/agents#509]
I would like to access the critic values of SAC in tf-agents and return them along with the action. What is the simplest way of doing that?
Thank you in advance for your help.

**Comment by summer-yue** [comment]
Thanks for the question. Since you have access to the critic network, the state and action, it should be straight forward to run a forward pass on the critic network to get the critic values.

If you wish to have this emit as part of the returned value from `policy.action`, you would need to modify the policy class such that it will be able to calculate the critic value and then return it, most likely as part of the policy info. You'll need to change the corresponding output spec to include the new value. This is not as straightforward as the first option.

Hope this helps.
