### ISSUE TITLE
How to load trained model or resume training?

### ISSUE THREAD

**Issue by ChengshuLi** [tensorflow/agents#52]
Hi,

I understand this issue has be raised here #4 , but I think I still have trouble loading trained model or resuming training. 

For instance, I ran [train_eval_gym.py](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v1/train_eval_gym.py) until convergence. Then I killed the processes and reran train_eval_gym.py with the same `--root_dir` to resume training. However, based on the tensorboard plot below, I don't think the checkpoint are properly loaded.

Train:
![image](https://user-images.githubusercontent.com/6732996/55045634-ae3b0580-4ffb-11e9-816f-bc47a211ff39.png)

Eval:
![image](https://user-images.githubusercontent.com/6732996/55045733-15f15080-4ffc-11e9-9bd8-78d9631e2250.png)

Disclaimer: I am using an older fork of your repo (beedf60a6fb9cc0f6efdc4d6d74e72613c83236f). If this issue has already been resolved in the latest version, please let me know. Thanks a lot!

**Comment by sguada** [comment]
We added the capability to checkpoint metrics at https://github.com/tensorflow/agents/commit/93d940ebbffe1640b26fa2da9bb9a14ec106b150

**Comment by ChengshuLi** [comment]
@sguada 

Thank you for getting back to me. 

Is this problem caused by checkpointing metrics? My feeling is that it has to do with loading the policy. The reason is that when I load a previously trained model/policy checkpoint, it performs significantly worse than it did when I stopped the previous training. 

For instance, I was training a point-to-point navigation agent in my own customized environment. I print "goal reached" whenever the agent reaches its goal position. Before I killed the training process, my agent was able to print "goal reached" 90% of the time (success rate ~90%). But when I resumed training, my agent could barely reach the goal anymore. I could be wrong, but I don't think this issue is about loading the metrics / tensorboard stuff but actually loading the model / policy? 

**What would you do if you want to evaluate a previously trained policy checkpoint or resume training from a previously trained policy checkpoint? I just want to make sure I am following the right procedure.** 

Thanks again for your generous help.

**Comment by sguada** [comment]
It could be that policy is not saved or restored properly. But if you are using the example binaries it should do the right thing.
See 
https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v1/train_eval_gym.py#L210

**Comment by kbanoop** [comment]
Closing this issue, please reopen if you have further questions.

**Comment by adecyber** [comment]
Reopening because same issue was encountered with the checkpoint being improperly loaded. I similarly kill training and then rerun only to observe a drop off in the performance of the saved policy. The teacher policy in the code below was previously trained as the policy for an SAC agent and saved to disk. Then it is reloaded and evaluated in a rollout as demonstrated. The performance is much different. 

One possible explanation that comes to mind is that exploration noise from the SAC agent is somehow reset at reloading time - however, it is not clear how this should impact the policy itself.
Another idea is that whether the policy is saved after being wrapped by the greedy policy wrapper as in `teacher_policy = greedy_policy.GreedyPolicy(tf_agent.policy)` may affect things. However, I have experimented with and without the greedy_policy class and have not observed a difference.

Thanks for the help!

![Screen Shot 2020-05-19 at 11 29 37 PM](https://user-images.githubusercontent.com/29108672/82413079-9a393b00-9a29-11ea-9c6c-f9754e091fff.png)
