### ISSUE TITLE
Error when define vector reward spec

### ISSUE THREAD

**Issue by zhouker94** [tensorflow/agents#557]
I was trying to build a multi-agent environment, which could return multi-dimensional rewards -> `R = [ r1, r2, r3 ... r_i, ... ]`. My environment is not a batched environment, but `restart`/`transition`/`termination` functions in [time_step](https://github.com/tensorflow/agents/blob/master/tf_agents/trajectories/time_step.py) wrongly inferring the batch_size/outer_dims from reward.shape or reward.shape[0].

As a workaround, I need to pass the `outer_dims` & `batch_size` explicitly:

for `ts.transition` set `outer_dims=()`
for `ts.termination` set `outer_dims=()`
for `ts.restart` set `batch_size=None`

The arguments seem not consistent as well.

More information could be found in this conversation between me and @kbanoop: https://github.com/tensorflow/agents/pull/552

**Comment by ebrevdo** [comment]
Indeed; we used to infer the batch dimensions from `reward.shape`.  In order to allow for multi-dim rewards, we now accept a `reward_spec` in `restart`, `outer_dims` in `transition` and `termination`.  By passing `reward_spec` to `restart` we can infer the outer_dims from observation shapes and `reward_spec` (or `batch_size`, i suppose).

These are inconsistent because some of these arguments receive a `reward` and some don't (in particular, `restart` is the only one that doesn't receive an actual reward; so instead we have `reward_spec` there.

It seems like this is a bug about better documentation of how outer_dims are inferred in these 3 functions; and we'd love a contribution improving the docstring.

**Comment by zhouker94** [comment]
Hi @ebrevdo thanks for your reply. I have made a [PR ](https://github.com/tensorflow/agents/pull/577) to improve the docstring.
