### ISSUE TITLE
Maybe a validate_py_environment Bug?

### ISSUE THREAD

**Issue by stefanhacko** [tensorflow/agents#604]
Hi,
I am creating a py_enviorment that starts a separate process (which is created with _reset method, I am not sure if this is the intended use, I am using agents for the first time).
I am trying to validate the environment  with the `validate_py_environment ` but the process is left running after the `validate_py_environment ` call.

Editing the last if statement in the implementation of  `validate_py_environment `  like this, 
```
    if time_step.is_last():
      episode_count += 1
      time_step = environment.reset()
      if episode_count == episodes:
        environment.close()
```

fixed my problem. Is this a good way to fix it, or am I doing something else wrong?

**Comment by ebrevdo** [comment]
Environments are expected to reset themselves when they emit `is_last`.

Instead of creating a `py_environment` that creates a separate process itself, instead have it work in-process, properly resetting as needed, and wrap it in a [ParallelPyEnvironment](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/parallel_py_environment.py#L50) which will properly create your env in one or more subprocesses.
