### ISSUE TITLE
Reinforce and PPO train_eval under example/v2 do not support checkpoint

### ISSUE THREAD

**Issue by bayesian** [tensorflow/agents#95]
Other agents train_eval all support checkpoints, why do those two on-policy algorithms V2 training does not support checkpoint?

**Comment by kbanoop** [comment]
I don't think there is any reason, it's just something we haven't gotten around to doing yet. We are happy to accept pull requests to add it. 

Meanwhile we are working on generic trainers that can train different agents, so all the bells and whistles of training scripts will be standardized there.

**Comment by tfboyd** [comment]
Update this when we tested the new PPO example.  The new example does checkpoints for sure that are great for doing offline or "sidecare" eval from another process or machine. The caveat is when it is restarted I am not sure it starts off exactly where it left off due to some replay buffer checkpointing.  Assigning to myself.  This issue is over a year old but the ask is valid and we are working on it so I want to see if I can get a true final answer in the next month or so.

**Comment by tfboyd** [comment]
https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/examples
