### ISSUE TITLE
Impossible to pass arguments to Gym Environment Wrappers

### ISSUE THREAD

**Issue by julianstastny** [tensorflow/agents#99]
The code in `agents/tf_agents/environments/suite_gym.py` does not support passing arguments to Gym Wrappers. 
[See this example](https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py ) as a potential use case where one wants to pass arguments to their wrapper.

I could implement it myself, but am unsure what the best way is. Intuitively, passing tuples of `(Wrapper, args)` or `(Wrapper, kwargs)` into `gym_env_wrappers` makes sense to me.

**Comment by kbanoop** [comment]
One way to do it is using lambdas or functools.partial like this:
https://github.com/tensorflow/agents/blob/3a64c31ba4a677665e01914533f8c15e70c55555/tf_agents/environments/suite_gym_test.py#L50

**Comment by julianstastny** [comment]
I wasn't aware of functools, thank you very much!

Anoop Korattikara <notifications@github.com> schrieb am Di., 7. Mai 2019,
20:59:

**Comment by sibyjackgrove** [comment]
I am also searching for a way to pass argument when loading my custom Gym environment.
For e.g. I have an argument named `max_sim_time` that I can pass to `gym.make()
`
`gym.make('PVDER-v0',max_sim_time=10.0)`

The above works because I have already specified it my register wrapper for my custom environment as shown below:
```
register(
    id='PVDER-v0',
    entry_point='gym_PVDER.envs:PVDER',
    kwargs={ 'max_sim_time' : 30.0 },
    max_episode_steps=500,)
```
 However when I try passing `max_sim_time `as an argument to `suite_gym.load()`, I get _unexpected keyword argument_ error.

```
from tf_agents.environments import suite_gym
import gym
import gym_PVDER
environment = suite_gym.load('PVDER-v0', max_sim_time=10.0)
```

Could you tell me the proper way to pass custom arguments to suite_gym.load()?

**Comment by seungjaeryanlee** [comment]
@sibyjackgrove The `suite_gym.load()` method (defined [here](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/suite_gym.py#L33)) does not accept custom arguments. One workaround might be to create a Gym environment wrapper that changes the `max_sim_time` parameter and pass the wrapper through `gym_env_wrappers` parameter.

That said, I think it would be better to open a new issue if you need further help.

**Comment by sibyjackgrove** [comment]
@seungjaeryanlee thanks for the suggestion. I opened a new issue in #137.

**Comment by sguada** [comment]
A PR which pass gym_kwargs to the gym environment is welcome.
